CREATE DATABASE feedbackSystem;

USE feedbackSystem;

CREATE TABLE University(
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(120) NOT NULL,
    Location CHAR(2) NOT NULL
);

CREATE TABLE Student (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Surname VARCHAR(30) NOT NULL,
    DateBirth DATE NOT NULL,
    Nationality VARCHAR(60) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    UniversityId BIGINT NOT NULL,
    FOREIGN KEY (UniversityId) REFERENCES University(Id)
);


CREATE TABLE Course(
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE Lecturer (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Surname VARCHAR(30) NOT NULL,
    Email VARCHAR(100) NOT NULL
);


CREATE TABLE Lecture (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(60) NOT NULL,
    DateCreated DATE NOT NULL,
    LecturerId BIGINT,
    FOREIGN KEY (LecturerId) REFERENCES Lecturer(Id)
);


CREATE TABLE Feedback(
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Content VARCHAR(100) NOT NULL,
    StudentId BIGINT,
    LectureId BIGINT,

    FOREIGN KEY (StudentId) REFERENCES Student(Id),
    FOREIGN KEY (LectureId) REFERENCES Lecture(Id)
);


CREATE TABLE Course_Lecturer (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    CourseId BIGINT,
    LecturerId BIGINT,
    FOREIGN KEY (CourseId) REFERENCES Course(Id),
    FOREIGN KEY (LecturerId) REFERENCES Lecturer(Id)
);


CREATE TABLE University_Course (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    UniversityId BIGINT,
    CourseId BIGINT,
    FOREIGN KEY (UniversityId) REFERENCES University(Id),
    FOREIGN KEY (CourseId) REFERENCES Course(Id)
);

