CREATE TABLE Course(
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE Lecturer (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Surname VARCHAR(30) NOT NULL,
    Email VARCHAR(100) NOT NULL
);

CREATE TABLE Course_Lecturer (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    CourseId BIGINT,
    LecturerId BIGINT,
    FOREIGN KEY (CourseId) REFERENCES Course(Id),
    FOREIGN KEY (LecturerId) REFERENCES Lecturer(Id)
);

