CREATE TABLE University(
    Id BIGINT AUTO_INCREMENT PRIMARY KEY
    Name VARCHAR(30) NOT NULL
    Location VARCHAR(160) NOT NULL
)
CREATE TABLE Course(
    Id INTEGER AUTOINCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE Lecturer (
    Id INTEGER PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Surname VARCHAR(30) NOT NULL,
    Email VARCHAR(100) NOT NULL
);
CREATE TABLE Feedback(
    Id INTEGER AUTO_INCREMENT PRIMARY KEY
    Content VARCHAR(100) NOT NULL
    studentId INTEGER FOREIGN KEY
    LectureId INTEGER FOREIGN KEY
)



